[package]
name = "py-arctic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "py_arctic"
crate-type = ["cdylib"]

[dependencies]
# polars = "0.21.1"
# polars-arrow = "0.21.1"
# polars = {git = "https://github.com/pola-rs/polars"}
# polars-arrow = {git = "https://github.com/pola-rs/polars"}
polars = {git = "https://github.com/pola-rs/polars", rev = "eb31d98a612e3f5aaa9da08391c0e9e7173a65a1"}
polars-arrow = {git = "https://github.com/pola-rs/polars", rev = "eb31d98a612e3f5aaa9da08391c0e9e7173a65a1"}
py-polars = {git = "https://github.com/pola-rs/polars", rev = "eb31d98a612e3f5aaa9da08391c0e9e7173a65a1"}
pyo3 = { version = "0.16.4", features = ["extension-module"] }
arctic = { path = "../" }
